#!/bin/bash
function OSSTART() {
	export BOOTARGS="${BOOTARGS} $1 $2 $3 $4 $5 $6 $7 $8 $9"
	export SYSNAME="LiteOS"
	export SYSVERS="1.1.0"
	export SYSLOC="$SYSTEM/boot/bootloader/liteos"
	export SYSCAC="$CACHE"

	verbose "Loading $SYSNAME: $SYSNAME $SYSVERS"

	cd "$SYSLOC/BASEDRIVERS"
	while read DATAFILE
	do
		source "$SYSLOC/BASEDRIVERS/$DATAFILE"
	done <<< "$(ls -p | grep -v / | grep ".DATA")"
	verbose "BaseDrivers are uploaded to memory."


	cd "$SYSLOC"
	while read DATAFILE
	do
		source "$SYSLOC/$DATAFILE"
	done <<< "$(ls -p | grep -v / | grep ".DATA")"
	verbose "$SYSNAME data is uploaded to memory."

	if [[ $(bootArgumentHas "lite") == "1" ]]; then
		LITE_START
	else
		LITE_BOOT_SYSTEM
	fi
}

function OSEND() {
	if [[ $(bootArgumentHas "no-cache-reset") == "0" ]]; then
		rm -rf "$CACHE"
	fi
	verbose "[*] Loading lists of backgroundworkers..."
	sys_log "OSStop" "Listing backgroundworkers..."
	ALIVE="$(ps -ax | grep "$SYSTEM/CoreFrameworks[/]")
	$(ps -ax | grep "$SYSTEM/CoreExecutives[/]")
	$(ps -ax | grep "$SYSTEM/BaseStructure[/]")
	"
	sys_log "OSStop" "Background workers: $ALIVE"
	verbose "[*] Killing syncronously..."
	sys_log "OSStop" "Killing all threads syncronously..."
	verbose "$ALIVE" | while read proc
	do
		if [[ ! -z "$proc" ]]; then
			frpid=($proc)
			kill -9 ${frpid[0]}
			sys_log "OSStop" "Killed: ${frpid[0]}"
			verbose "[*] Killed PID: ${frpid[0]}"
		fi
	done
	sys_log "OSStop" "All workers closed."
	verbose "[*] Background workers are closed."
}

export -f OSSTART
export -f OSEND
export BOOT_LOADER="liteos"